# Simple GET with variable
GET {{BASE_URL}}/get
Accept: application/json

###

# POST with variables in URL and body
POST {{BASE_URL}}/post
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "name": "{{TEST_NAME}}",
  "email": "{{TEST_EMAIL}}"
}

###

# Test nested variables
GET {{API_PROTOCOL}}://{{API_HOST}}/status/200

###

# Test variable in headers
GET {{BASE_URL}}/headers
X-Custom-Token: {{AUTH_TOKEN}}